[tool.autopep8]
indent_size = 2
max_line_length = 100
# ignore = "E121,E125,E126,E129,E226,E302,E305,E501,W504,E741,E704"
ignore = "E121,E125,E126,E129,E226,E302,E305,E501,W504,E741,E703,W503"
exclude = ".ipynb_checkpoints,Other,blackjack_other*"
aggressive = 3
recursive = true

[tool.mypy]
exclude = "(^Other|^blackjack_other)"
ignore_missing_imports = true
strict = true
check_untyped_defs = true
# python_version = "3.7"

[tool.pylint.main]
# See pylint options using "pylint --generate-toml-config"
disable = [
  "unspecified-encoding", "fixme", "redefined-builtin", "cell-var-from-loop",
  "using-constant-test", "simplifiable-condition", "import-outside-toplevel", "line-too-long",
  "too-many-lines", "too-few-public-methods", "too-many-arguments", "too-many-locals",
  "too-many-instance-attributes",
  "missing-module-docstring", "unnecessary-semicolon",
]
reports = false
score = false
recursive = true
ignore-paths = [".ipynb_checkpoints", "Other", "blackjack_other.*"]
# py-version = "3.7"

[tool.pylint.basic]
good-names-rgxs = "^[a-z][a-z0-9]?|[A-Z]([A-Z_]*[A-Z])?$"

[tool.pylint.format]
indent-string = "  "
expected-line-ending-format = "LF"
