[tool.autopep8]
indent_size = 2
ignore = "E121,E125,E126,E129,E226,E302,E305,E501,W504,E741,E20,W503"
exclude = ".ipynb_checkpoints,Other,blackjack_other*"
aggressive = 3
recursive = true

[tool.mypy]
exclude = "(^Other|^blackjack_other)"
ignore_missing_imports = true
strict = true

[tool.pyink]
pyink-indentation = 2
line-length = 100  # Default is 88.
pyink-use-majority-quotes = true
extend-exclude = "\\.ipynb"

[tool.pylint.main]
disable = [
  "unspecified-encoding", "fixme", "redefined-builtin", "cell-var-from-loop",
  "using-constant-test", "simplifiable-condition", "import-outside-toplevel", "line-too-long",
  "too-many-lines", "too-few-public-methods", "too-many-arguments", "too-many-locals",
  "too-many-instance-attributes", "too-many-statements",
  "missing-module-docstring"
]
reports = false
score = false
recursive = true
ignore-paths = [".ipynb_checkpoints", "Other", "blackjack_other.*"]

[tool.pylint.basic]
good-names-rgxs = "^[a-z][a-z0-9]?|[A-Z]([A-Z_]*[A-Z])?$"

[tool.pylint.format]
indent-string = "  "
expected-line-ending-format = "LF"
